### ISSUE TITLE
求更新一下

### ISSUE THREAD

**Issue by zhang988925** [dcloudio/H5P.Android#1]
求更新一下，实在是坑太深，哪有前端返回用户信息的，都怎么想的，唉
提供的微信鉴权不满足条件 我们要自己修改一下WeiXinOAuthService

**Comment by anlexN** [comment]
@zhang988925 ，我也这样觉得。@YanYiLin repo只有一个人维护，这也太没有效率了吧。

**Comment by tony2u** [comment]
最近都在加班，把代码移植到Cordova了，就是坑啊！

**Comment by anlexN** [comment]
此repo, 很多信息不透明。
