### ISSUE TITLE
项目很棒

### ISSUE THREAD

**Issue by hyzx86** [dcloudio/H5P.Android#3]
zxing 使用的apache 开源，然而这个产品似乎没有遵从其开源协议？

[https://github.com/zxing/zxing/blob/master/LICENSE](url)

**Comment by ArrayDC** [comment]
此项目没有修改ZXing的代码，所有源码都都包含了完整的apache开源协议。

**Comment by ArrayDC** [comment]
引用开源项目ZXing的目录为feature/barcode/src/com/dcloud/zxing，所有源码文件头中都包含完整的apache开源协议，并没有违反其开源协议。

**Comment by hyzx86** [comment]
抱歉噢，我使用该仓库的代码已经修改成功并跑起来了。但是忘记回来删除该issue
开源不易，致敬
